[package]
name = "blinkybool/feather"
version = "0.2.0-rc2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["feather.lua", "default.project.json", "wally.toml"]
