[package]
name = "billy/feather"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
description = "Memory efficient, roact-like library for declaratively creating/updating large numbers of instances."

[dependencies]
